---
- name: Mac dev playbook
  hosts: all
  become: true

  vars_files:
    - "vars/dev.yml"

  pre_tasks:
    - name: Print Ansible info useful for development
      debug:
        msg:
          - "{{ ansible_distribution }} {{ ansible_distribution_version }}"

  tasks:
    - name: Install common utilities
      package:
        name:
          - screen
          - wget
          - links
          - parallel
          - htop
      become: false

    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.28.5/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        owner: root
        group: wheel

    - name: Install Ansible Molecule
      pip:
        name: molecule

    - name: Install yamllint and ansible-lint
      package:
        name:
          - yamllint
          - ansible-lint
      become: false

    - name: Install pre-commit
      pip:
        name: pre-commit

    - name: Check out moosefs-playbook
      git:
        repo: git@github.com:Zorlin/moosefs-playbook.git
        dest: /Users/wings/projects/moosefs-playbook
      become: false

    - name: Check out ansible-role-moosefs
      git:
        repo: git@github.com:Zorlin/ansible-role-moosefs.git
        dest: /Users/wings/projects/ansible-role-moosefs
      become: false

    - name: Check out slurm-playbook
      git:
        repo: git@github.com:Zorlin/slurm-playbook.git
        dest: /Users/wings/projects/slurm-playbook
      become: false

    - name: Check out ansible-role-slurm
      git:
        repo: git@github.com:Zorlin/ansible-role-slurm.git
        dest: /Users/wings/projects/ansible-role-slurm
      become: false

    - name: Check out upload-toolkit
      git:
        repo: git@github.com:riffcc/upload-toolkit.git
        dest: /Users/wings/projects/upload-toolkit
      become: false

#    - name: Install Chia
#    - name: Install Sia

  roles:
    # No roles yet.
